### PR TITLE
Added WPS Office logo

### PR DESCRIPTION
**Pull request by pyroxar**

### CODE REVIEW

**Comment by gasinvein** [comment]
Adding an icon file to this repo doesn't affect anything, it have to be installed into the correct place inside the flatpak bundle.
Doesn't Linux Mint Software support remote icons in appdata? If it doesn't, than it should be considered a Linux Mint Software bug, since remote icons are part of appdata specification.

**Comment by pyroxar** [comment]
It's support appstream:
```
 # For Flatpak, look in Appstream and mintinstall provided flatpak icons
            if pkginfo.pkg_hash.startswith("f"):
                icon_path = "/var/lib/flatpak/appstream/%s/%s/active/icons/64x64/%s.png" % (pkginfo.remote, pkginfo.arch, pkginfo.name)
                if os.path.exists(icon_path):
                    return GdkPixbuf.Pixbuf.new_from_file_at_size(icon_path, size, size)

                icon_path = "/usr/share/linuxmint/mintinstall/flatpak/icons/64x64/%s.png" % pkginfo.name
                if os.path.exists(icon_path):
                    return GdkPixbuf.Pixbuf.new_from_file_at_size(icon_path, size, size)
```
How I can add the icon to flatpak appstream?

**Comment by gasinvein** [comment]
Icon is already present in appdata, it's just hosted on remote server instead of local filesystem:
https://github.com/flathub/com.wps.Office/blob/b13c19c8fd6e83e410ebc77ed6969544098ec434/com.wps.Office.appdata.xml#L17
Better ask mintinstall developers to support remote icons like this one, they are part of [the spec](https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html).

**Comment by TingPing** [comment]
Whatever that snippet you linked is doing looks like a terrible hack that it absolutely should not be doing...

**Comment by pyroxar** [comment]
@TingPing it's code of the mintinstall
https://github.com/linuxmint/mintinstall/blob/master/usr/lib/linuxmint/mintinstall/mintinstall.py

**Comment by pyroxar** [comment]
It's whole code of the function which set icons of aplications:
```
def get_application_icon(self, pkginfo, size):
        # Look in the icon theme first
        theme = Gtk.IconTheme.get_default()

        try:
            for name in [pkginfo.name, pkginfo.name.split(":")[0], pkginfo.name.split("-")[0], pkginfo.name.split(".")[-1].lower()]:
                if theme.has_icon(name):
                    iconInfo = theme.lookup_icon(name, size, 0)
                    if iconInfo and os.path.exists(iconInfo.get_filename()):
                        return GdkPixbuf.Pixbuf.new_from_file_at_size(iconInfo.get_filename(), size, size)

            # For Flatpak, look in Appstream and mintinstall provided flatpak icons
            if pkginfo.pkg_hash.startswith("f"):
                icon_path = "/var/lib/flatpak/appstream/%s/%s/active/icons/64x64/%s.png" % (pkginfo.remote, pkginfo.arch, pkginfo.name)
                if os.path.exists(icon_path):
                    return GdkPixbuf.Pixbuf.new_from_file_at_size(icon_path, size, size)

                icon_path = "/usr/share/linuxmint/mintinstall/flatpak/icons/64x64/%s.png" % pkginfo.name
                if os.path.exists(icon_path):
                    return GdkPixbuf.Pixbuf.new_from_file_at_size(icon_path, size, size)

            # Look in app-install-data and pixmaps
            for extension in ['svg', 'png', 'xpm']:
                icon_path = "/usr/share/app-install/icons/%s.%s" % (pkginfo.name, extension)
                if os.path.exists(icon_path):
                    return GdkPixbuf.Pixbuf.new_from_file_at_size(icon_path, size, size)

                icon_path = "/usr/share/pixmaps/%s.%s" % (pkginfo.name, extension)
                if os.path.exists(icon_path):
                    return GdkPixbuf.Pixbuf.new_from_file_at_size(icon_path, size, size)
        except GLib.Error:
            pass

        return self.generic_available_icon_pixbuf
```

**Comment by pyroxar** [comment]
Icons are in linux mint's folder 
obraz

**Comment by TingPing** [comment]
Yeah I got that, it is simply wrong and should be fixed. You don't bundle icons in the app store that is nonsensical. They should detect remote icons and download them like normal.

**Pull request closed without merging**
