### PR TITLE
build freetype 2.13.0 for wps to workaround fake blod problem

### PR DESCRIPTION
**Pull request by madoka773**
#150  @mlawson27

### CODE REVIEW

**Comment by madoka773** [comment]
bot, build

**Comment by madoka773** [comment]
@gasinvein @bbhtt @mlawson27 @barthalion 
Can anyone help review this pull request?

**Comment by bbhtt** [comment]
Not sure why this would be needed? The 23.08 runtime comes with freetype 2.13? 

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/freedesktop-sdk-23.08.20/elements/include/freetype.yml?ref_type=tags

**Comment by madoka773** [comment]
> Not sure why this would be needed? The 23.08 runtime comes with freetype 2.13?
> 
> https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/freedesktop-sdk-23.08.20/elements/include/freetype.yml?ref_type=tags

https://github.com/NixOS/nixpkgs/issues/279314
https://forums.opensuse.org/t/wps-office-bold-font-corruption/169420
https://bbs.wps.cn/topic/3137

WPS office requires freetype<=2.13 to make bold style font display properly

**Pull request merged**
