### PR TITLE
Set correct backup paths in config via wrapper

### LINKED ISSUE #34: Backup Management does not work
I have just found hard way that backup management does not work in Flatpak distribution of WPS office, latest version as of today.
While installed from RPM, Backup Management works as expected.
Default backup location is /home/<user>/.kingsoft/office6/data/backup/

### PR DESCRIPTION
**Pull request by gasinvein**
We can use a wrapper to alter `Office.conf`, setting backup path to persistent location under `$XDG_DATA_HOME`.
Fixes #34

### CODE REVIEW

**Comment by gasinvein** [comment]
@TingPing what's considered be worse: mounting data directory from host or editing user config via wrapper?

**Comment by gasinvein** [comment]
@GoodMirek I hope this would solve #56. You're welcome to test if you'd like.

**Comment by GoodMirek** [comment]
@gasinvein On my system, I have the following version of WPS office flatpak installed. Its date is more recent than the date of build 13099. How do I find whether this pull request is included in my installed version?
```
flatpak info com.wps.Office

WPS Office - WPS Office Suite

ID: com.wps.Office
Ref: app/com.wps.Office/x86_64/stable
Arch: x86_64
Branch: stable
Version: 11.1.0.8865
License: LicenseRef-proprietary=http://wps-community.org/license.md
Origin: flathub
Collection: org.flathub.Stable
Installation: system
Installed: 281.9 MB
Runtime: org.freedesktop.Platform/x86_64/19.08
Sdk: org.kde.Sdk/x86_64/5.13

Commit: a68a2232e0fdebdb79bd3b960f3d05055a876f57d4cce13efb27dff68de29973
Parent: e78fe43ac90162e96a096b37bf37d52913d38da6b657cf6455ceeed41175a84f
Subject: Drop udev submodule (be1aace8)
Date: 2019-12-31 21:28:19 +0000
```

**Comment by GoodMirek** [comment]
I just realized that as this PR is still open, it is most probably not present in the stable.
However, I cannot install the test build:
```
$ flatpak install --user https://dl.flathub.org/build-repo/12497/com.wps.Office.flatpakref
error: Can't load uri https://dl.flathub.org/build-repo/12497/com.wps.Office.flatpakref: Server returned status 404: Not Found
```

**Comment by gasinvein** [comment]
Yeah, test builds from PRs have to be installed separately, This one just got removed due to timeout.
bot, build

**Comment by GoodMirek** [comment]
@gasinvein Thanks a lot for your quick response.

# Test description

## OS under test
Virtual machine without WPS office installed.
Spin of Fedora 31 Silverblue
Version: Kinoite 31.12 (2019-12-27T22:32:52Z)
Desktop environment: KDE Plasma 5.17.4
Flatpak: flatpak-1.4.3-3.fc31.x86_64

## Steps
Installed system-wide, as usually:
`sudo flatpak install https://dl.flathub.org/build-repo/12732/com.wps.Office.flatpakref`

Check of the application info:
`flatpak info com.wps.Office`
```
WPS Office - WPS Office Suite

          ID: com.wps.Office
         Ref: app/com.wps.Office/x86_64/test
        Arch: x86_64
      Branch: test
     Version: 11.1.0.8865
     License: LicenseRef-proprietary=http://wps-community.org/license.md
      Origin: office-origin
  Collection: org.flathub.Stable.Build12732
Installation: system
   Installed: 282.0 MB
     Runtime: org.freedesktop.Platform/x86_64/19.08
         Sdk: org.kde.Sdk/x86_64/5.13

      Commit: 6da9d1708aa882c6fcf72085a728ee341068878bbbc7d85778ed6b86b2088dca
     Subject: Change backup path in config via wrapper (a1f4a531)
        Date: 2020-01-04 10:49:48 +0000
```
Run the application:
`flatpak run com.wps.Office`
```
No config exists, creating one
```
Accepting *Kingsoft Office Software License Agreement and Privacy Agreement*.
System Check displays usual warning about formula symbols might not display correctly due to missing fonts.
Creating a new document called *test.docx* in WPS Writer. Saving the document, making changes to the document and saving it again.
Selecting *Menu* in top left corner, choosing item Backup Management. Then, clicking button *Open Backup Folder* in right pane.
Nothing happens after clicking the button.
There is no `.local` in `~/.var/app/com.wps.Office`.
There is no files nor directories in `~/.var/app/com.wps.Office/data/`.
There is no `~/.local/share/Kingsoft/`.
There is no `~/.kingsoft`.

In configuration file `/home/mirek/.var/app/com.wps.Office/config/Kingsoft/Office.conf`
there is the next line:
`common\Backup\AutoRecoverFilePath=/home/mirek/.var/app/com.wps.Office/data/Kingsoft/office6/data/backup`


# Test results
## Backup test failed
No backup files are created.

## UI test failed
Expected correct result was that after clicking the button the backup folder would open.

**Comment by gasinvein** [comment]
@GoodMirek What if you open some file and edit it prior to opening backup filder, so WPS attempts to create some backups there?

**Comment by GoodMirek** [comment]
> What if you open some file and edit it prior to opening backup folder, so WPS attempts to create some backups there?

@gasinvein It is what I did. I did exactly the steps as outlined above.

I have just tried to manually create the directory structure `/home/mirek/.var/app/com.wps.Office/data/Kingsoft/office6/data/backup`, restart WPS Office and retry the test, to no avail.

**Comment by gasinvein** [comment]
@GoodMirek Sorry, I've meant editing document prior to saving it. My guess is that in your case WPS didn't actually even try to create a backup. Anyway, pushed an update, so that backup dir is created at launch.

**Comment by gasinvein** [comment]
Looks like WPS creates backups when you did some changes to a document, but didn't save it for several seconds.

**Comment by GoodMirek** [comment]
@gasinvein Sorry, I misunderstood what you meant before. It is clear now.

Yes, backup files are created now.
However, the UI button still does not work. Reading through #34 I think it should work, as the backup folder is now accessible within the sandbox.
Can I do anything to troubleshoot that?

**Comment by gasinvein** [comment]
Can you please retest (removing `~/.var/app/com.wps.Office`) and confirm that backups are created in `~/.var/app/com.wps.Office/Kingsoft/office6/data/backup` and are accessible both from inside and outsude of the sandbox?
You can run a shell in the sandbox with `flatpak run --command=bash com.wps.Office`.

**Comment by GoodMirek** [comment]
I have deleted `rm -rf ~/.var/app/com.wps.Office` and installed `sudo flatpak install https://dl.flathub.org/build-repo/12737/com.wps.Office.flatpakref`.
I have confirmed that backup files are created at `/home/mirek/.var/app/com.wps.Office/data/Kingsoft/office6/data/backup`.

I can list files under the regular user:
```
[mirek@localhost ~]$ ls -l /home/mirek/.var/app/com.wps.Office/data/Kingsoft/office6/data/backup
total 36
-rw-r--r--. 1 mirek mirek 11079 Jan  4 22:08 test.docx.7DEEB95D2C7B4C8390B1F4503DF0D125.20200104220856232.wps
-rw-r--r--. 1 mirek mirek 11091 Jan  4 22:09 test.docx.7DEEB95D2C7B4C8390B1F4503DF0D125.20200104220901759.wps
-rw-r--r--. 1 mirek mirek 11103 Jan  4 22:09 test.docx.7DEEB95D2C7B4C8390B1F4503DF0D125.20200104220920896.wps
```
and also from inside of the sandbox:
```
[mirek@localhost ~]$ flatpak run --command=bash com.wps.Office
[📦 com.wps.Office ~]$
[📦 com.wps.Office ~]$ ls -l /home/mirek/.var/app/com.wps.Office/data/Kingsoft/office6/data/backup
total 24
-rw-r--r-- 1 mirek mirek 11091 Jan  4 22:09 test.docx.7DEEB95D2C7B4C8390B1F4503DF0D125.20200104220901759.wps
-rw-r--r-- 1 mirek mirek 11103 Jan  4 22:09 test.docx.7DEEB95D2C7B4C8390B1F4503DF0D125.20200104220920896.wps
```
However, the button *Open Backup Folder* in the WPS right pane *Backup Management* still does not work.

**Comment by gasinvein** [comment]
> installed `sudo flatpak install https://dl.flathub.org/build-repo/12737/com.wps.Office.flatpakref`.

It was the previous build. Latest is https://github.com/flathub/com.wps.Office/pull/56#issuecomment-570781561. But looks like it worked anyway.

> However, the button Open Backup Folder in the WPS right pane Backup Management still does not work.

Hmm. This might have something to do with the portal or DE. Can you open that folder with `xdg-open` from inside the sandbox?
Also, I've installed this test build to a clean VM with Fedora 31 KDE and "Open Backup Folder" worked there.

**Comment by GoodMirek** [comment]
> > installed `sudo flatpak install https://dl.flathub.org/build-repo/12737/com.wps.Office.flatpakref`.
> 
> It was the previous build. Latest is [#56 (comment)](https://github.com/flathub/com.wps.Office/pull/56#issuecomment-570781561). But looks like it worked anyway.

I believe it is the same build as I have installed.

> > However, the button Open Backup Folder in the WPS right pane Backup Management still does not work.
> 
> Hmm. This might have something to do with the portal or DE. Can you open that folder with `xdg-open` from inside the sandbox?
> Also, I've installed this test build to a clean VM with Fedora 31 KDE and "Open Backup Folder" worked there.

`xdg-open /home/mirek/.var/app/com.wps.Office/data/Kingsoft/office6/data/backup` works from regular command line, but not from inside of the sandbox entered with the command `flatpak run --command=bash com.wps.Office`.
I am testing in Fedora 31 Workstation KDE on bare metal now too, but not clean install (upgraded FC27-->FC28-->FC29-->FC30-->FC31).
Please would you have any advice how to troubleshoot that?

**Comment by gasinvein** [comment]
Does `xdg-open`'ing folders from inside the sandbox work for other apps?

**Pull request merged**
