### PR TITLE
Install spellcheck dictionaries

### LINKED ISSUE #5: Add spell checker dictionaries

### PR DESCRIPTION
**Pull request by gasinvein**
Most of the dictionaries are FLOSS, but some lacks license information (so assumed to be proprietary). So install all as extra-data for now.
Fixes #5

### CODE REVIEW

**Comment by LeandroStanger** [comment]
@gasinvein The spell checker works now

**Comment by gasinvein** [comment]
Dictionaries without license information:
- de_DE
- en_GB
- fr_FR
- it_IT
- km_KH
- nl_NL
- pt_BR
- ro_RO
- ru_RU
- sv_SE
- tr_TR
- uk_UA

**Comment by LeandroStanger** [comment]
How is the progress?

**Comment by gasinvein** [comment]
It's currently working, but I'm not sure if it should be merged, as it would make app installation ureliable.
The main problem is that dictionaries urls are not versioned, so, whenever a dictionary is updated, it's checksum will missmatch and thus installation of the app will fail.

**Comment by LeandroStanger** [comment]
@ramcq Could help?

**Comment by toMeloos** [comment]
This is kind of a big deal for everyone using other languages than just English and the solution is already here. Can anyone give this pull request some love and get it merged?

**Comment by gasinvein** [comment]
Superseded by #45

**Pull request closed without merging**
