### PR TITLE
Update some things

### LINKED ISSUE #48: Update runtime to 19.08

### PR DESCRIPTION
**Pull request by gasinvein**
- Drop "2019" suffix from icons, probably unneeded for flatpak
- Update i18n to latest commit
- Update shared-modules

### CODE REVIEW

**Comment by Erick555** [comment]
@gasinvein [qt4 fails to build against 19.08 runtime](https://github.com/flathub/shared-modules/issues/81), are syou surethis app still use qt4?

Also you can drop udev-175 submodule which isn't needed with 19.08

**Comment by gasinvein** [comment]
@Erick555, yeah, I see it, thanks.

**Comment by Erick555** [comment]
@gasinvein I checked package contents and all needed qt4 libs should be bundled there. You can try removing qt4 submodule and set `LD_LIBRARY_PATH` which points to bundled libs in launcher.

**Comment by gasinvein** [comment]
@Erick555 Qt4 here is needed at build time (for translations), it's cleaned out of the bundle:
https://github.com/flathub/com.wps.Office/blob/acb861a06553da253069accc4b829be47bea23b4/com.wps.Office.yml#L36-L37

**Comment by Erick555** [comment]
@gasinvein yes, but this is wrong thing to do when you want to update to 19.08 runtime. You have to switch to bundled qt4 libs

**Comment by Erick555** [comment]
Neither debian/ubuntu or Arch linux use external qt4 libs, they use bundled ones.

**Comment by gasinvein** [comment]
@Erick555 I can't use bundled Qt4 libs to build translations.

**Comment by Erick555** [comment]
@gasinvein ok, so if they don't host binaries for translations somewhere then you either have to drop translations or give up on updating to 19.08 runtime for now.

**Comment by Erick555** [comment]
@gasinvein I found translations available here: https://github.com/timxx/wps-office-mui

**Comment by gasinvein** [comment]
> give up on updating to 19.08 runtime for now

Yes, I've already force-pushed removing 064dd8e7c45f438944fbf9164bfc6fb4dccf44f0 commit.

> I found translations available here: https://github.com/timxx/wps-office-mui

I'd rather avoid relying on a 3rd-party repo.

**Comment by Erick555** [comment]
> Yes, I've already force-pushed removing 064dd8e commit.

You have to revert udev removal and revert submodules repo update then.

**Comment by gasinvein** [comment]
It looks like the app doesn't need udev anymore. At least nothing in the package is linked against it.

**Comment by Erick555** [comment]
Ok then.

**Pull request merged**
